POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Leo santos",
    "email": "leonardoaa@gmail.com",
    "username": "leosantos123aa",
    "password": "leosantosx",
    "description": ""
}