POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Leo santos",
    "email": "leonard2o@gmail.com",
    "username": "leosantosx2",
    "password": "leosantosx",
    "description": ""
}