POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Leo santos",
    "email": "leonardo@gmail.com",
    "username": "leosantosx",
    "password": "@Leosantosx",
    "enabled": false,
    "description": ""
}